# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Jikoku Documentation
repo_url: https://github.com/takeoischifan/jikoku
repo_name: takeoischifan/jikoku


theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
  palette:
    scheme: slate
    primary: green


plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
